### PR TITLE
Improved example with full features

### LINKED ISSUE #15: Use `>` hotkey in  blockquote will resolve blockquote to paragraph

### LINKED ISSUE #16: Upload image error

### LINKED ISSUE #17: Link still has issue

### PR DESCRIPTION
**Pull request by mrcfps**
- Add full-featured example
- Fix issues around `link` and `list` plugin

Closes #15.
Closes #16.
Closes #17.

### CODE REVIEW

**Review by studytoohard — APPROVED** [review]

**Comment by pftom** [comment]
@mRcfps @studytoohard  Editure still has these issue: #17 #16 #15  🤓

**Review by pftom — APPROVED** [review]
Thanks for your great works! well done🥳🥳

**Comment by mrcfps** [comment]
Closes #15, #16 and #17.

**Review by pftom — APPROVED** [review]
So smart guy, editure examples is rebirth

**Pull request merged**
